baseURL: "http://86.13.142.16/"
languageCode: "en-us"
title: "Maheen Waris | Personal Portfolio"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true


markup:
  goldmark:
    renderer:
      unsafe: true


params:
  title: "MW"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    defaultTheme: "dark"

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left


  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "MW" # Brand name for the brand | default is the title variable
    disableSearch: true
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Maheen."
    subtitle: "I build things for the web"
    content: "A passionate Website Developer. I tend to make use of HTML, CSS, Bootstrap & JS to build websites that look fantastic, feel amazing, and function correctly."
    image: /images/hero.svg
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    # button:
    #   enable: true
    #   name: "Resume"
    #   url: "#"
    #   download: true
    #   newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/Maheenwaris9
        
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/%D8%A7%D9%85%D8%B1-%D8%A8%DB%8C%D9%84-70799725b


  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me.png"
    content: |-
      I am a developer with a passion for web development. I have a background in computer science and Information Technology, and also I have a strong interest in the intersection  of technology and Computer. I am currently working as a Website developer C-Soft.
      
       I am currently working on projects that will be used in Education, Cosmetics & Game Development Websites.

    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "HTML"
        - "CSS"
        - "JavaScript"
        - "Bootstrap"


  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Course of Fronrt-End Web Developer"
        company: "C-Soft Career Institute"
        companyUrl: "https://www.career.edu.pk/"
        date: "March 2022 - present"
        content: "I am currently working on many projects, some of which are about the school website, some about Game Development & portfolios, etc."


  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Bachelors in IT"
        school:
          name: "Information Technology From the University of Sargodha"

      - title: "Web Development C ourse"
        school:
          name: "Career institute, Faisalabad"

      - title: "ADS degree"
        school:
          name: "The Summit College, Faisalabad"

      - title: "Intermediate Graduation"
        school:
          name: "Islamia Girls college, Faisalabad"

      - title: "High School"
        school:
          name: "Laboratory Girls High school, Faisalabad."


  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: mahamaqbool921@gmail.com
    btnName: Mail me


  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"